export const dataa = [
  {
    name: "Davidi",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  {
    name: "David",
    surname: "Keci",
    age: 30,
    city: "New York",
    country: "USA",
    occupation: "Engineer",
    email: "david@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc.",
    salary: "$80,000",
  },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },
  // {
  //   name: "David",
  //   surname: "Keci",
  //   age: 30,
  //   city: "New York",
  //   country: "USA",
  //   occupation: "Engineer",
  //   email: "david@example.com",
  //   phone: "123-456-7890",
  //   address: "123 Main St",
  //   company: "ABC Inc.",
  //   salary: "$80,000",
  // },

  // Rest of the data...
];
import { currentData } from "../../Components/SideBarElementsContainers/Faturat/Table/Table";

export function DowloadDataExel() {
  console.log("lol" + currentData);

  if (currentData.length === 0) {
    console.error("No currentData to export.");
    return;
  }

  const headers = Object.keys(currentData[0]).join(",") + "\n";
  const csv =
    headers + currentData.map((row) => Object.values(row).join(",")).join("\n");

  const csvBlob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const csvURL = URL.createObjectURL(csvBlob);

  const link = document.createElement("a");
  link.href = csvURL;
  link.setAttribute("download", "table_currentData.csv");
  document.body.appendChild(link);
  link.click();

  document.body.removeChild(link);
}
