export const data = [
    {
      name: "Davidi",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
      name: "David",
      surname: "Keci",
      age: 30,
      city: "New York",
      country: "USA",
      occupation: "Engineer",
      email: "david@example.com",
      phone: "123-456-7890",
      address: "123 Main St",
      company: "ABC Inc.",
      salary: "$80,000",
    },
    {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
      {
        name: "David",
        surname: "Keci",
        age: 30,
        city: "New York",
        country: "USA",
        occupation: "Engineer",
        email: "david@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        company: "ABC Inc.",
        salary: "$80,000",
      },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },{
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
    //   {
    //     name: "David",
    //     surname: "Keci",
    //     age: 30,
    //     city: "New York",
    //     country: "USA",
    //     occupation: "Engineer",
    //     email: "david@example.com",
    //     phone: "123-456-7890",
    //     address: "123 Main St",
    //     company: "ABC Inc.",
    //     salary: "$80,000",
    //   },
      
    // Rest of the data...
  ];